version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/codebase-rag
   file_existsBehavior: OVERWRITE
hooks:
  AfterInstall:
   - location: deploy.sh
     timeout: 300
     runas: root
